= code-speedy: A VS Code Extension to Automate Almost Anything Four Differentg Ways

== Features

Visual Studio Code does not have a macro-recording capability for automating tasks.
Snippets come close.
There have been a few takes on creating extensions that approximate the idea of recording macros (except that "`recording`" is really "`programming`").
(See History, below.)
This is my take.

Basically, this extension allows you configure any number of "`macros`" and assign them each a shortcut key sequence.
Here we'll define a macro as a list of "`actions.`"
And an action is, in turn, a list of "`steps.`"

There are several action types:

* *command* -- Executes a VS Code command with or without arguments.
(Anything you can assign a shortcut sequence to is a "`command.`")
* *javascript* -- Executes some arbitrary JavaScript code, with full access to the VS Code API.
* *shellscript* -- Executes a shell script (in a hidden terminal window).
* *snippet* -- Inserts an arbirary snippet, that is, where you define the snippet template right there as this action's steps.
(If you want to invoke an existing snippet by its prefix, there's a command for that.)
* *variables* -- Defines a set of variables using JavaScript expressions for the duration of the macro.
The calculated values are then inserted into named placeholders in any of the other action steps (command arguments, javascript code, shell script code, snippet template text).
* *description* -- Does nothing (just a convenient way to document what the macro does).
* *speedy* -- Sets various directives (e.g. `verbose = true`, `context = python`) for the duration of the macro.
(`context` is not implemented yet.)
* *shortcut* -- (not implemented yet) Directly assigns a keyboard shortcut, if one is not already assigned.

A macro can mix and match all of these.
For example, the `pytestForFunction` macro in the `python.speedy` sample, uses five different actions (speedy, commmand, variables, javascript, snippet).



== Installation

First, install the code-speedy extension via the marketplace.

Then, open your VS Code settings.json and create a new `code-speedy` section, as follows:

. Click on the gear-icon (lower left).
. Select "`Settings.`"
. Press the open-settings icon in the top right corner.
(It used to look like {}, but now it looks like a dog-eared page with a wrap-around arrow.)
. Add a section that goes something like this:

[source:json]
----
"speedy.macros": {
    "files": [
    	"/work/universal-macros.speedy",
    	"~personal-macros.speedy",
    	"project-macros.speedy",
    	"../project-group-macros.speedy"
    ]
}
----

* You can name these files anything you want. Using a `.speedy` extension is just a suggestion.
* Paths are relative to the current working folder.
* (Not implemented yet) On Windows, a leading ~ is changed to `%USERPROFILE%\`
* If speedy can't find a particular file, it just skips it.
For example, if speedy is given the configuration above, then it'll look for a `project-macros.speedy` in the current working folder, but if there isn't one, that's not a problem.


== Invoking a Macro

You can run a macro via the command pallet (ctrl+shift+P).
Type `speedy` to jump down to the `speedy:` commands and select `speedy: run macro`.
Pick the macro you want to run.

To create a keybinding to a macro...
. Open the Keyboard Shortcuts (Gear-icon -> Keyboard Shortcuts).
. Start to type "speedy".
All of the code-speedy macros have a "speedy." prefix.



== Macro Elements: Commands and Modifiers

Macro(s) are defined in plain text file(s).
A macro starts with the a macro name in square brackets.
That is followed by one or more actions.
An action starts with the action type followed by a colon, on a line by itself.
It is important that both the macro name and the action type be left aligned (not indented).
Any lines that follow an action type are considered the steps for that action -- until another action type or another macro name declaration is encountered.

It's typical to indent the action steps for two reasons: (1) it makes it easier to read, (2) if an action step happens to look like a macro name declaration or an action type declaration, the indentaion will prevent it from being confused with one.
The action steps of a snippet action (i.e. the text of the snippet tempate) is the only exception.
If you indent any of those lines, then that indenation will be part of the template.
Speaking of which, for all other action types, speedy will skip blank lines and comment lines (that begin with //), but any such lines in a snippet will be preserved.

----
[pytestForFunction]
speedy:
	// These comments are ignored
	// Note: currently, if you set verbose = false, that will set it to "false" a non-empty string.
	// So, just delete this line altogther.
	verbose = true
cmd:
    cursorHome
vars:
	author = (group effort)
	// "standard" (with no =) brings in twenty+ standard definitions (e.g. TODAY, WORKSPACE_NAME, TM_DIRECTORY)
	standard
javascript:
	// This comment and the blank line that follows are ignored

    const editor = window.activeTextEditor;         // this comment is part of the javascript (not ignored by
    const doc = window.activeTextEditor.document;   // speedy, but then ignore by the JS interpreter)
    let parts = doc.lineAt(window.activeTextEditor.selection.start).text.split('(');

	// speedy is a special object that you can reference in your JS (along with vscode, window, and path)
	speedy.setVariable('function_name',parts[0].replace('def ','').trim());
    parts = parts[1].split(')');
    let args = parts[0].split(',');
    parts = parts[1].replace('->','').split(':');
    let hint = parts[0];
    let arg_names = [];
    let arg_vals = [];
    args.forEach(function(arg){
        let parts = arg.split('=');
        let val = (parts.length >= 2) ? parts[1].trim() : '';
        parts = parts[0].split(':');
        let arg_name = parts[0].trim();
        let hint = (parts.length >= 2) ? parts[1].trim() : '';
        if (val == ''){val = (hint == 'int') ? '123' : '\"abc\"'};
        arg_names.push(arg_name);
        arg_vals.push(val);
    });
    parts = (doc.isUntitled ? '' : doc.fileName).split('.')[0].split('\\\\')
	speedy.setVariable('unit_name',parts.slice(parts.length-3).join('.'));
	speedy.setVariable('arg_name_list',arg_names.join(','));
	speedy.setVariable('arg_val_list',arg_vals.join(','));
	speedy.setVariable('first_arg_val',arg_vals[0]);
snip:
# TODO Move this to test_$TM_FILENAME
from ..${TM_FILENAME_BASE} import $function_name
def test_$function_name():
	( ${arg_name_list} ) = ( $arg_val_list )
    assert $function_name($arg_name_list) == $first_arg_val


----

All speedy identifiers (macro names, variable names) may only consist of letters, numbers, and underscores.

The following action type declarations are recognized:

* *speedy:*
* *description:* (or "desc:")
* *command:* (or "cmd:")
* *javascript:* (or "js:")
* *shellscript:* (or "shell:")
* *snippet:* (or "snip:")
* *variables:* (or "vars:")

For a command, the name of the command goes on the next line (the first "step").
Any arguments go on the following lines (steps 2, 3, ...).

For JavaSript, a shell script, or a snippet, the code or template text begins with the next line (steps 1 thru N).

For variables, either put the word "standard" on a line by itself, and/or list your own variable definition(s).
A variable definition consists of a name, followed by an equal sign (=), followed by a JavaScript expression.
Again, the name can only consist of letters, numbers, and underscores.
Specifying ("standard") causes twenty+ pre-defined variables to be loaded.
(See complete list below.)


Your JavaScript (in both the javascript action and the variable definitions) has access to the `speedy` object, the `vscode` object, the `window` object and the `path` object.

* The `speedy` object allows for the definition of variable on the fly. It also has some helper functions that sometimes come in handy.
* The `vscode` object (`vscode.commands`, `vscode.env`, `vscode.workspace`, `vscode.tasks`, etc.) is documented here: https://code.visualstudio.com/api/references/vscode-api.
* The `window` object is just a synonym for `vscode.window`.
* The `path` object is part of node.js.



== Some Examples

* If the only thing on a line is "[identifier]" then that starts a new macro. ("`Identifier`" consists of letters, numbers, and/or underscores only.) It must not be indented.
* The line that kicks off a new action ("actiontype:") must not be indented, either.
* Any indentation and blank lines in the text of a snippet template is preserved.
* All other indentation/blank lines is ignored (trimmed), i.e. in the bodies of the non-snippet action types.

----
[openNewTerminal]
description:
	A simple example tha demonstrates opening a new terminal window.
command:
	workbench.action.terminal.new
command:
	workbench.action.terminal.sendSequence
	text = "echo hello\n"

[printToNewTerminal]
cmd:
	 workbench.action.terminal.new
vars:
	$currentFile = window.activeTextEditor.document.uri.fsPath
	$currentFolder = vscode.workspace.rootPath
command:
	workbench.action.terminal.sendSequence
	text = "echo the current file is: $currentFile\necho the current folder is: $currentFolder\n"

[showMessageViaJavascript]
js:
	window.showInformationMessage(`You entered: ${await window.showInputBox()}`

[userInputViaJavascript]
javascript:
	let response = await window.showInputBox()
	await window.showInformationMessage(`You entered: ${response}`)

[shellExample]
description:
	Example of running a shell script in the background.
	IMPORTANT: don't start a shell command here that doesn't finish!
	There's no good way of killing/canceling it.
	(Yes, the echo in step 2 will never be seen.)
shell:
	touch .gitignore
	echo hello

[anotherShellExqample]
vars:
	$currentFolder = vscode.workspace.rootPath
shell: cd \"$currentFolder\"
	touch .gitignore

[invokeSomeNamedSnippet]
command:
	type
	text = "mySnippetPrefixHere"
command:
	insertSnippet


[unMultiSelectLast]
description:
	For when you Ctrl-Click to multiselect 10 times and on the eleventh get it wrong.
	Just press Ctrl-0 (or whatever key you assign) to unselect the eleventh, then carry on.
	(See also, https://github.com/danseethaler/vscode-tab-through-selections, for more along this line.)
javascript:
	const editor = window.activeTextEditor;
	const newSelections = editor.selections.slice(0, editor.selections.length - 1);
	editor.selections = newSelections;

[transformToSnake]
description:
	A multi-select friendly macro to convert from CamelCase to snake_case.
	If any particular selection is empty (just a cursor), this will automatically expand it to the whole word first.
	(Kudos to https://stackoverflow.com/users/398630/brainslugs83 for some pointers)
javascript:
	let editor = window.activeTextEditor;
	expandWords();
	doTransform(0);
	function expandWords() { let sels = editor.selections; let i = sels.length-1;
	  while (i >=0) { let sel = sels[i];
	    if (sel.isEmpty) {r = editor.document.getWordRangeAtPosition(sel.start); sels[i] = new vscode.Selection(r.start, r.end);}
	    i--; }
	  editor.selections = sels;
	}
	function doTransform(i) { let sels = editor.selections;
	  if (i < 0 || i >= sels.length) { return; }
	  let sel = sels[i];
	  let word_matches = editor.document.getText(sel).matchAll(/([a-z]+|[A-Z][a-z]*|[^A-Za-z]+)/g);
	  let words = [];
	  for (const match of word_matches) {words.push(match[0].toLowerCase())};
	  editor.edit(eb => {eb.replace(sel, words.join('_'))}).then(x => { doTransform(i+1); });
	}

[transformToCamel]
description:
	Same as transformToSnake, but vice versa
javascript:
	let editor = window.activeTextEditor;
	expandWords();
	doTransform(0);
	function expandWords() { let sels = editor.selections; let i = sels.length-1;
	  while (i >=0) { let sel = sels[i];
	    if (sel.isEmpty) {r = editor.document.getWordRangeAtPosition(sel.start); sels[i] = new vscode.Selection(r.start, r.end);}
	    i--; }
	  editor.selections = sels;
	}
	function doTransform(i) { let sels = editor.selections;
	  if (i < 0 || i >= sels.length) { return; }
	  let sel = sels[i];
	  let words = editor.document.getText(sel).split('_')
	  let camel_words = words.map(function(w) {return w[0].toUpperCase() + w.slice(1,).toLowerCase()});
	  editor.edit(eb => {eb.replace(sel, camel_words.join(''))}).then(x => { doTransform(i+1); });
	}

[userInput]
javascript:
	let response = await window.showInputBox()
	await window.showInformationMessage(`You entered: ${response}`)


[clipCurrentWord]
js:
	const doc = window.activeTextEditor.document
	let cursorPos = window.activeTextEditor.selection.start)
	let word = doc.getText(doc.getWordRangeAtPosition(cursorPos))
	(TBD push the word into the clipboard)
----

== How to Know What VS Code Commands are Available

Open the VS Code keybindings.json file...

. Click on the gear-icon (lower left).
. Select "`Keyboard Shortcuts`"
. Press the open-settings icon in the top right corner.
(It used to look like {}, but now it looks like a dog-eared page with a wrap-around arrow.)
. All of the commands can be copied and pasted from here.

== The Standard Variables

Here are the variables that get defined when you specify "standard" in a "vars:" action:
NOTE: The ones that begin with TM_ are exact duplicates of the corresponding variables already available in snippets.
This just makes them avbailable to your javascript, your shell scripts, and the command arguments, as well.

[width="100%",cols="2,5",options="header"]
|===
| Variable Name                | Value
| CLIPBOARD                    | The contents of your clipboard
| CURSOR_CHAR_NUMBER           | The position of the cursor from the start of the line
| DOC_ENTIRE_TEXT              | The text of the entire document
| EOL_STYLE                    | Either 'LF' or 'CRLF'
| LINE_COUNT                   | The number of lines in the document, currently.
| MACHINE_ID                   | The name of computer you are running on
| MULTI_SELECT_COUNT           | How many multi-selects there are currently
| PREFERED_LANGUAGE            | e.g. 'en-US'
| SESSION_ID                   | A unique string that changes when VS Code restarts
| SHELL_NAME                   | The name of the default terminal shell
| TM_CURRENT_LINE              | The text of the current line
| TM_CURRENT_WORD              | The text of the word under cursor (or an empty string)
| TM_DIRECTORY                 | The directory of the current document
| TM_FILENAME                  | The filename of the current document (no path)
| TM_FILENAME_BASE             | The filename of the current document without its extensions
| TM_FILEPATH                  | The full file path of the current document (dir, filename, and ext)
| TM_LINE_INDEX                | The zero-index based line number
| TM_LINE_NUMBER               | The one-index based line number
| TM_SELECTED_TEXT             | The currently selected text (or an empty string). If multi-select, only returns the first selection.
| TODAY                        | Today's date
| WORKSPACE_NAME               | The name of the opened workspace or folder
|===

To obtain one of these variable values, use a placeholder in the form of `$variablename` or `${variablename}`.
Either one will work.
TIP: The second form is required if the placeholder is immediately followed by a letter, number, or underscore.

In case you are curious, here are the actual definitions:

[width="100%",cols="2,5",options="header"]
|===
| Variable Name                | JavaScript Expression
| CLIPBOARD                    | vscode.env.clipboard.readText()
| CURRENTFILEDIR               | path.dirname(window.activeTextEditor.document.uri.fsPath)
| CURSOR_CHAR_NUMBER           | window.activeTextEditor.selection.start.character
| LINE_COUNT                   | window.activeTextEditor.document.lineCount
| MACHINE_ID                   | vscode.env.machineId
| PREFERED_LANGUAGE            | vscode.env.language
| SESSION_ID                   | vscode.env.sessionId
| SHELL_NAME                   | vscode.env.shell
| TM_CURRENT_LINE              | window.activeTextEditor.document.lineAt(window.activeTextEditor.selection.start)
| TM_CURRENT_WORD              | window.activeTextEditor.document.getText(window.activeTextEditor.document.getWordRangeAtPosition(window.activeTextEditor.selection.start))
| TM_DIRECTORY                 | vscode.workspace.rootPath
| TM_FILENAME                  | path.basename(window.activeTextEditor.document.uri.fsPath)
| TM_FILENAME_BASE             | path.basename(window.activeTextEditor.document.uri.fsPath).replace(/\\.[^/.]+$/, '')
| TM_FILEPATH                  | window.activeTextEditor.document.uri.fsPath
| TM_LINE_INDEX                | window.activeTextEditor.selection.start.line
| TM_LINE_NUMBER               | window.activeTextEditor.selection.start.line + 1
| TM_SELECTED_TEXT             | window.activeTextEditor.document.getText(window.activeTextEditor.selection)
| TODAY                        | new Date().toDateString();
| WORKSPACE_NAME               | vscode.workspace.name
|===


== History

This extension is heavily inspired by Jeff Hykin's "`Macro Commander`" extension (https://github.com/jeff-hykin/macro-commander), which is a fork of an extension by link:http://gedd.ski[geddski].
See also http://gedd.ski/post/level-up-coding-with-macros/[Level up your Coding with Macros]


== Requirements

TBD

== Extension Settings

TBD

== Known Issues

* speedy: "verbose = false" currently sets it to 'false' (string not boolean).
* Ought to replace using eval() (in two places) with IIFE.

Not yet implemented:

* Syntax highlighting for .speedy files
* Wildcards in config file names
* Integrate with tasks(?)
* In Windows, change a leading ~ to `%USERPROFILE%\`
* "shortcut:" action
* context = python option ("speedy:" action)

Marketing To Do:

* Publish to the marketplace
* Add screenshots/animation to the readme.
* Put a donate button somewhere.
* Register a code-speedy.xxx domain and put up a landing page.


== Release Notes

TBD

=== 0.0.1 (Alpha test)

TBD


